[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Allow writing deployment files to the project root
fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read", path = "./out" }
]

# Compiler settings
optimizer = true
optimizer_runs = 200
via_ir = true


[lint]
ignore = ["test/**"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
